services:
  redis:
    image: redis:latest

    ports:
      - "6379:6379"

    volumes:
      - "E:/minikube/docker_projects/springboot_app_plus_redis/redis-app/data:/data"

  app:
    build: .

    ports:
      - "8080:8080"

    depends_on:
      - redis