FROM nginx:latest
COPY index.html /usr/share/nginx/html/index.html
COPY favicon.png /usr/share/nginx/html/favicon.png
#COPY songs/The_Weeknd_ft._playboi_carti_-_Popular.mp3  /usr/share/nginx/html/songs/
#COPY songs/The_Weeknd_ft._Playboi_Carti_-_Timeless.mp3  /usr/share/nginx/html/songs/
